name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev python3-setuptools
          sudo apt-get install -y libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
          sudo apt-get install -y zlib1g-dev openjdk-17-jdk zip unzip
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          # Чистимо старі невдалі спроби і запускаємо білд
          buildozer android clean
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-game-apk
          path: bin/*.apk
          
